# This is a sample configuration file The syntax is TOML
# (https://github.com/toml-lang/toml/wiki)

conn_uri = 'postgres://csvtopg:fq5WYLL!@localhost/csvtopg'
input_file = '~/data/mylargecsv.csv'
table_name='mylargecsv'
use_uvloop = true
log_level = 'DEBUG'